export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAILURE = "CREATE_MOVIE_FAILURE";

export const FETCH_GENRE_REQUEST = "FETCH_GENRE_REQUEST";
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILURE = "FETCH_GENRE_FAILURE";