export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAILURE = "CREATE_MOVIE_FAILURE";

export const FETCH_GENRE_REQUEST = "FETCH_GENRE_REQUEST";
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILURE = "FETCH_GENRE_FAILURE";

export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH_SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH_SINGLE_MOVIE_SUCCESS";
export const FETCH_SINGLE_MOVIE_FAILURE = "FETCH_SINGLE_MOVIE_FAILURE";